### ISSUE TITLE
Feature Request | Invoice Endpoints

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-bexio#7]
- [ ] Feature Request | Invoice Endpoints

**Comment by grn-dk** [comment]
Thank you. Sounds good.
We might do the invoice endpoints later this year: https://docs.bexio.com/#tag/Invoices

I have created this fork https://github.com/grn-dk/laravel-bexio for testing invoices and it seems that invoicing also requires item positions (https://docs.bexio.com/#tag/Item-positions/operation/v2CreateItemPosition), or some other position position endpoint in the Bexio system (https://docs.bexio.com/#tag/Invoices). This of course depends on the business use case. If we finalize the invoicing for our need in the fork, we will make a pull request into this project.

Initially we thought it would be enough to create an invoice and attach an amount to that invoice, but it seems that we need to investigate this a bit more before finalizing our need for invoicing endpoints and endpoints supporting invoice creation before an invoice is ready to be sent by mail etc.

**Comment by StanBarrows** [comment]
Hey @grn-dk 

Many thanks for your message.

Yes, it's also required to have invoice positions, but you need to create the positions within the invoice body. Besides that, you also need a lot of other Bexio Objects that you need to include within the request. 

I've already made a project for handling the invoices, but I needed more time to integrate it into the package properly. I've used the Calebs Sushi Package to fetch the Laravel Invoice Model from Bexio directly. Attached some snippets form the implementation. 

## BexioInvoice Model

```
<?php

namespace App\Models\Providers\Bexio;

use App\Models\User;
use App\Scopes\SushiClearEmptyValuesScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Sushi\Sushi;

/**
 * @property int $id
 * @property string document_nr
 * @property string title
 * @property int contact_id
 * @property int user_id
 */
class BexioInvoice extends Model
{
    use Sushi;

    const KB_ITEM_STATI = [
        self::KB_ITEM_STATUS_DRAFT,
        self::KB_ITEM_STATUS_PENDING,
        self::KB_ITEM_STATUS_PAID,
        self::KB_ITEM_STATUS_PARTIAL,
        self::KB_ITEM_STATUS_CANCELED,
        self::KB_ITEM_STATUS_UNPAID,
    ];

    const KB_ITEM_STATUS_DRAFT = 7;

    const KB_ITEM_STATUS_PENDING = 8;

    const KB_ITEM_STATUS_PAID = 9;

    const KB_ITEM_STATUS_PARTIAL = 16;

    const KB_ITEM_STATUS_CANCELED = 19;

    const KB_ITEM_STATUS_UNPAID = 31;

    //const ENDPOINT_GET_FETCH = 'https://api.bexio.com/2.0/kb_invoice?limit=7500&order_by=id_desc';
    const ENDPOINT_GET_FETCH = 'https://api.bexio.com/2.0/kb_invoice?limit=7500&';

    const ENDPOINT_GET_INVOICE_FETCH = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}';

    const ENDPOINT_GET_PDF = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}/pdf';

    const ENDPOINT_POST_ISSUE_AN_DRAFTED_INVOICE = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}/issue';

    const ENDPOINT_POST_DRAFT_AN_PENDING_INVOICE = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}/revert_issue';

    const ENDPOINT_POST_CANCEL_AN_PENDING_INVOICE = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}/cancel';

    const ENDPOINT_DELETE_DELETE_AN_DRAFTED_INVOICE = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}';

    const ENDPOINT_POST_ISSUE_AN_INVOICE = 'https://api.bexio.com/2.0/kb_invoice/{invoice_id}/issue';

    const ENDPOINT_POST_CREATE = 'https://api.bexio.com/2.0/kb_invoice';

    protected $schema = [
        'id' => 'integer',
        'name' => 'string',
        'kb_item_status_id' => 'integer',
        'total' => 'float',
        'is_valid_from' => 'date',
        'is_valid_to' => 'date',
    ];

    protected static function booted()
    {
        static::addGlobalScope(new SushiClearEmptyValuesScope());
    }

    public function getRows(): array
    {
        $user = auth()->user();

        if (! $user instanceof User) {
            return [['id' => null]];
        }

        $response = Cache::remember($user->uuid.'_bexio_invoice', 60, function () use ($user) {
            return $this->sendRequest($user);
        });

        return $response->successful() ? $this->mapResponse($response->json()) : [['id' => null]];
    }

    protected function sendRequest(User $user)
    {
        $response = Http::acceptJson()->withToken($user->bexio_api_key)->get(self::ENDPOINT_GET_FETCH);

        activity()
            ->causedBy($user)
            ->withProperties([
                'endpoint' => self::ENDPOINT_GET_FETCH,
                'status' => $response->status(),
                'response' => $response->json(),
            ])
            ->log(__CLASS__);

        return $response;
    }

    protected function mapResponse($response)
    {
        $models = collect($response)->map(function ($model) {
            return [
                'id' => $model['id'],
                'document_nr' => $model['document_nr'],
                'kb_item_status_id' => $model['kb_item_status_id'],
                'contact_id' => $model['contact_id'],
                'title' => $model['title'],
                'user_id' => $model['user_id'],
                'total' => $model['total'],
                'is_valid_from' => $model['is_valid_from'],
                'is_valid_to' => $model['is_valid_to'],
            ];
        });

        return $models->toArray();
    }

    /**
     * Get the bexioContact record associated with the bexioInvoice.
     */
    public function bexioContact()
    {
        return $this->belongsTo(BexioContact::class, 'contact_id', 'id');
    }
}
```

### getInvoiceBody Method

`    protected function getInvoiceBody($invoice_positions)
    {
        return [
            'title' => $this->invoice->title,
            'contact_id' => $this->invoice->contact->bexio_contact_id,
            'user_id' => $this->configuration->default_creator_id,
            'pr_project_id' => null,
            'logopaper_id' => $this->configuration->default_invoice_logopaper_id,
            'language_id' => $this->configuration->default_invoice_language_id,
            'bank_account_id' => $this->configuration->default_invoice_client_bank_account_new_id,
            'currency_id' => $this->configuration->default_invoice_currency_id,
            'payment_type_id' => $this->contact->bexio_payment_type_id,
            'header' => $this->configuration->default_invoice_header,
            'footer' => $this->configuration->default_invoice_footer,
            'mwst_type' => $this->configuration->default_invoice_mwst_type,
            'mwst_is_net' => $this->configuration->default_invoice_mwst_is_net,
            'show_position_taxes' => $this->configuration->default_invoice_show_position_taxes,
            'is_valid_from' => $this->invoice->date->format('Y-m-d h:m:s'),
            'is_valid_to' => $this->invoice->date->addDays($this->contact->invoice_time_period_in_days)->format('Y-m-d h:m:s'),
            'positions' => $invoice_positions,
        ];
    }`


### getInvoicePositions Method

`    protected function getInvoicePosition($time_sum, $bexio_account_id, $text, $price_per_hour)
    {
        return [
            'amount' => $time_sum,
            'unit_id' => $this->configuration->default_invoice_unit_id,
            'account_id' => $bexio_account_id,
            'tax_id' => $this->configuration->default_invoice_tax_id,
            'text' => $text,
            'unit_price' => $this->getRoundedPrice($price_per_hour),
            'discount_in_percent' => null,
            'type' => 'KbPositionCustom',
        ];
    }`
    
    
    And then you just submit the object.

` $response = Http::acceptJson()->withToken($this->user->bexio_api_key)->post($endpoint, $this->invoiceBody);`

**Comment by grn-dk** [comment]
Hi @StanBarrows 

Thank you.

OK. Initially we can create an invoice, and then we thought we could run a post request for a position which would attach the position to a specific invoice. But it might be more complicated than that.

**Comment by StanBarrows** [comment]
Hey @grn-dk 

I think your'e able to do this. But this is an improvement this was not possible when we've implemented this feature. 

<img width="383" alt="CleanShot 2024-02-11 at 10 12 01@2x" src="https://github.com/codebar-ag/laravel-bexio/assets/10268813/339c3c68-6ff9-44c8-b5a3-64ae8d6d6663">

I'm just not sure if you can create an invoice with an empty positions body. 

![CleanShot 2024-02-11 at 10 13 09@2x](https://github.com/codebar-ag/laravel-bexio/assets/10268813/d75fc664-d2a7-4a06-bfe0-d93865d85137)

**Comment by grn-dk** [comment]
Hi @StanBarrows. Yes, we are waiting with testing the create an item position for now. But I can confirm that creating an invoice without any item positions is possible via the current API. We have tested this and it is working with the implementation made in the fork of this repository.
Thank you.

**Comment by kaspernowak** [comment]
@StanBarrows Has this been implemented in 1.0 since this has been closed?

**Comment by StanBarrows** [comment]
Hey @kaspernowak 

We're happy to review and merge a Pull-Request with the missing Invoice requests and DTO's. 

Altough we have a rough concept in mind about the implementation, its not on our short roadmap to implement it. Therefore I'm going to close the current issue.

**Comment by kaspernowak** [comment]
@StanBarrows I have implemented all position dto's requests, and tests locally, and updated `CreateAnInvoiceRequest`. 

I can create invoices like so now:
```php
$connector = new BexioConnector();

    $contacts = $connector->send(new FetchAListOfContactsRequest)->dto();
    $user = $connector->send(new FetchAuthenticatedUserRequest)->dto();
    $languages = $connector->send(new FetchAListOfLanguagesRequest)->dto();
    $banks = $connector->send(new FetchAListOfBankAccountsRequest)->dto();
    $currencies = $connector->send(new FetchAListOfCurrenciesRequest)->dto();
    $paymentTypes = $connector->send(new FetchAListOfPaymentTypesRequest)->dto();
    $units = $connector->send(new FetchAListOfUnitsRequest)->dto();
    $accounts = $connector->send(new FetchAListOfAccountsRequest)->dto();
    $taxes = $connector->send(new FetchAListOfTaxesRequest(scope: 'active', types: 'sales_tax'))->dto();

    $invoiceDto = new CreateInvoiceDTO(
        title: 'Test',
        contact_id: $contacts->first()->id,
        user_id: $user->id,
        pr_project_id: null,
        language_id: $languages->first()->id,
        bank_account_id: $banks->first()->id,
        currency_id: $currencies->first()->id,
        payment_type_id: $paymentTypes->first()->id,
        footer: 'Footer Test',
        header: 'Header Test',
        mwst_type: 1,
        mwst_is_net: true,
        show_position_taxes: true,
        is_valid_from: now()->format('Y-m-d H:i:s'),
        is_valid_to: now()->addDays(5)->format('Y-m-d H:i:s'),
        api_reference: (string) Str::uuid(),
        positions: [
            new AddTextPositionDTO(
                text: (string) Str::uuid(),
                show_pos_nr: true,
                type: 'KbPositionText'
            ),
            new AddDefaultPositionDTO(
                type: 'KbPositionCustom',
                amount: 1,
                unit_id: $units->first()->id,
                account_id: 145,
                tax_id: $taxes->first()->id,
                text: Str::uuid(),
                unit_price: 100,
                discount_in_percent: '0',
            ),
        ],
    );

    $invoice = $connector->send(new CreateAnInvoiceRequestNew(invoice: $invoiceDto))->dto();

```
And if I want to send the invoice and mark it as sent, I can do that with:
```php
    $sendInvoiceDto = new SendInvoiceDTO(
        recipient_email: 'k.nowak1@gmail.com',
        subject: 'Your Invoice',
        message: 'Please find the document at [Network Link]',
        mark_as_open: true,
        attach_pdf: true
    );
    $sendInvoice = $connector->send(new SendAnInvoiceRequest(
        invoice_id: $invoice->id,
        invoice: $sendInvoiceDto
    ))->dto();

    $markInvoiceAsSent = $connector->send(new MarkAnInvoiceAsSentRequest(
        invoice_id: $invoice->id
    ))->dto();
```

I am struggling to ensure backwards compatibility, because the existing `CreateAnInvoiceRequest`does not work with the provided example in the docs. Specifically, this results in an error: 
https://github.com/codebar-ag/laravel-bexio/blob/ab3e88bc5975fac25f94f82964eb674e769b4267/src/Requests/Invoices/CreateAnInvoiceRequest.php#L68C9-L68C96

The error:
`CodebarAg\Bexio\Requests\Invoices\CreateAnInvoiceRequest::filterPositions(): Argument #1 ($positions) must be of type Illuminate\Support\Collection, array given, called in /Users/kaspernowak/development/meinrad/bexio-api/laravel-bexio-gpt/src/Requests/Invoices/CreateAnInvoiceRequest.php on line 68`

So my question is, do we need to keep backwards compatibility for invoice creation, or should I just focus on the updated approach?

**Comment by StanBarrows** [comment]
Hey @kaspernowak

Thanks for your work!

Could you create a dedicated PR for this?

**Comment by kaspernowak** [comment]
Hey @StanBarrows, yes I can. I branched my work off of my forks main, where I had merged the OAauth2 PR for no good reason, probably because I thought it would be a smooth merge xD. But I will refactor my Invoice branch and create a PR for it :)
